### ISSUE TITLE
Why'd you lose the beard?

### ISSUE THREAD

**Issue by yoshuawuyts** [hughsk/ama#15]
I mean...
![bearded_god](https://cloud.githubusercontent.com/assets/2467194/8717389/7be3a10e-2bde-11e5-94e7-cfde363f5fb7.jpeg)

**Comment by timoxley** [comment]
+1

**Comment by hughsk** [comment]
Hah! It started getting a bit scraggly and unmaintainable:

![image](https://cloud.githubusercontent.com/assets/569817/8766588/9102c206-2e3e-11e5-8e93-bd571eae0734.png)

So now I keep it short, that way it's less apparent that I'm technically homeless :) I tried getting completely rid of it for a week but then changed my mind after a friend pointed out that I was much more muggable when I looked about 15 years old.
