### ISSUE TITLE
What you think about RegExps project?

### ISSUE THREAD

**Issue by tunnckoCore** [hughsk/ama#16]
That's a big idea and project, and have many steps to do more.

- [RegExps Github Organization](https://github.com/regexps)
- [meta stuff repository](https://github.com/regexps/meta)
- [General discussion and roadmap](https://github.com/regexps/meta/issues/16)
- [more big and older "first hit" discussion](https://github.com/regexps/meta/issues/2)

In general  - centralized place for regular expression world for all languages. Just we are javascripters and we start with it.

[https://github.com/tunnckoCore/ama](https://github.com/tunnckoCore/messages)

**Comment by hughsk** [comment]
It's a nice idea and I've seen it around, but don't have strong opinions on it. Best of luck though!
