### ISSUE TITLE
Where do you live?

### ISSUE THREAD

**Issue by stevemao** [hughsk/ama#18]

**Comment by hughsk** [comment]
Nowhere, currently! I grew up in Sydney, and moved to Amsterdam early last year. Though I was already travelling a lot I officially left and started roaming more in January. It's been great but starting to wear me down. Plan is to move to either Brooklyn or Berlin sometime between October 2015 and February 2016 but I have a bunch of logistics to sort out before I can do that unfortunately.

**Comment by stevemao** [comment]
I can't believe you are not planning to move back to Sydney! Its so nice here :p

**Comment by hughsk** [comment]
Haha, nah :P It's lovely but having grown up there it's lost a lot of appeal for me, if I were to move back to Australia it would be Melbourne for sure :grin:
