### ISSUE TITLE
What do you think about npm having so many modules

### ISSUE THREAD

**Issue by kentcdodds** [hughsk/ama#21]
Hi, I recently [tweeted](https://twitter.com/kentcdodds/status/650034445974568960):

![screen shot 2015-10-05 at 9 19 12 am](https://cloud.githubusercontent.com/assets/1500684/10284634/2bcb5b14-6b42-11e5-937e-c01947835a82.png)

> So is there going to be some kind of crazy celebration when @npmjs hits a quarter of a million packages in the next 6 months or so?
> Or is this something to lament? #lessismore? @npmjs

Curious what your thoughts on the matter are :-)

**Comment by hughsk** [comment]
It's great!

There are of course downsides to this:

1. Discovery. We've got all this code out there but it's still hard to track down sometimes, especially for [newcomers](https://twitter.com/seldo/status/644932539635757056). Curated communities work well for this: one of the reasons for starting [stack.gl](http://stack.gl/) was to ease people in tracking down all the (somewhat niche) 3D packages we were writing. I know that npm has something in the works to build this into the platform eventually via [ecosystems](http://blog.npmjs.org/post/94662089625/the-future-of-the-npm-website-lets-map-this#ecosystems). Usable now but yet to see it in the wild :(
2. Management. Right now I've got [601 packages](https://npmjs.com/~hughsk) on my account, of which something in the vicinity of 350 that I authored. The amount of maintenance involved is comparable to maintaining a mid-range framework but made harder by having to keep track of the issues across hundreds of repos. Making an update on 100+ packages is really difficult right now but [we're working on it](https://github.com/sindresorhus/awesome-electron/issues/95). This also leads to some difficulties for package consumers and contributors on account of code getting neglected sometimes.

Ultimately though the more that's out there the better imo. Duplication is a good thing, it gives us more of a chance to iterate on our approaches and explore different tradeoffs. Fragmentation is still a bummer, I find that's amplified by frameworky packages (e.g. `grunt-*`, `react-*`, `angular-*`, `*`).

A lot of room for the above to be improved with better tooling and community curation :)

**Comment by kentcdodds** [comment]
I agree. I think that the burden should fall on the tool to help the best packages bubble to the top. Good thoughts! Thanks!
