### ISSUE TITLE
What's the favorite module you've made and why?

### ISSUE THREAD

**Issue by sindresorhus** [hughsk/ama#3]

**Comment by hughsk** [comment]
Not necessarily a module, but an Atom plugin: [npm-install](https://github.com/hughsk/atom-npm-install). I use it all the time and it's made pulling in new packages totally seamless. My coworkers have mixed feelings about the abundance of modules I pull in as a result :)

I really like [smokestack](https://github.com/hughsk/smokestack) and think there's lots of potential there but I've been neglecting it. It's been sweet seeing new iterations of it like [chromeo](https://github.com/mattdesl/chromeo) and [hihat](https://github.com/mattdesl/hihat).
