### ISSUE TITLE
What was your best programming moment?

### ISSUE THREAD

**Issue by sindresorhus** [hughsk/ama#5]

**Comment by hughsk** [comment]
I started writing out my narrowest high-stake save (my [graduation project](http://hughsk.io/articles/synthesis.html)), and then realised *actually that was totally awful, I wouldn't wish that upon anyone*. We glorify those super-tense launch periods a little too much. I'm always really happy to see a fresh project in action, especially when I'm able to see people enjoying it – the [opening titles](http://hughsk.io/articles/southim.html) screening for Web Directions South 2013 was a definite highlight for me. But I also get super stressed before a big launch and then pretty low afterwards, a post-partum depression of sorts if you will.

Outside of that, those moments in graphics programming where a long-mysterious concept suddenly clicks tend to stay with me: the first time I understood [fractal frames](https://www.youtube.com/watch?v=JTCCYGQiwE0), projecting down into 2D, [dot-product lighting](http://hughsk.io/glsl-point-light/) and [raytracing](https://www.shadertoy.com/view/XslSWs) to name a few.

**Comment by sindresorhus** [comment]
> the opening titles screening for Web Directions South 2013 was a definite highlight for me. 

That's super good!

-

And just wanted to mention that the https://unpm.nodesource.com/ visualization you did is just incredible.

**Comment by hughsk** [comment]
Thanks! Hopefully more of the likes of WDS13 and UNPM will be on their way soon :grin:
